### ISSUE TITLE
Wrong position when importing bvh file

### ISSUE THREAD

**Issue by bsgg** [emilianavt/BVHTools#4]
Hi,
I found a new issue, with the position of the model when importing the animation.
This is the situation:
- Take a model of Scale 1 and record an animation and export in bvh.
- Use the same model  with a different scale for example 1.5 (smaller or bigger). 
- The animation looks ok but the model has an offset to compensate between different scales.
There is something that needs to be corrected in order to make this works but I'm not so sure how.
Something related with the way you apply the offset of the root bone, when creating the animation  (on the loader)
I'm trying to figure out a way to fix it, any ideas?

Thanks in advance

**Comment by emilianavt** [comment]
Thank you for reporting this issue. Please try if 0b183c86fe79f9f5550bc85ced8b2d640366acc4 fixes this.

**Edit:** The recorder probably should do something similar for scaled models.

**Edit 2:** I included a corresponding adjustment to the recorder in 7311981a1a577ae2508ebd3ba905213557d2f064.

**Comment by bsgg** [comment]
Thanks!
Looking forward to try the fix as soon as I can.

While I was waiting for an answer from you I was trying to fix the issue, and I did something similar.
On the Animation loader I scaled the position with the target avatar (as you are doing) but I need the scale of the original avatar, so I ended up saving that value in an external file.

I didn't know how to save the scale on the bvh, thanks!

**Comment by emilianavt** [comment]
Thinking about it a bit more, that inverse scale should probably be applied to all bone positions in the recorder, otherwise a scaled model will look off in Blender.

**Edit**: Implemented in 81b53f8a4bff1c01984c9578ba23475ba4a3c641.

**Comment by bsgg** [comment]
I've tested the fix, it works!
Thanks

**Comment by emilianavt** [comment]
Thank you for testing it!

I'll finish up a new release then.
