### ISSUE TITLE
Import extracted BVH file at the Maya/3D Max

### ISSUE THREAD

**Issue by YouMinJung** [emilianavt/BVHTools#9]
Hi.

I imported the extracted BVH file at the Maya and 3D Max. but It occurred import error.
Is there a way to extract the bvh files that can be used in Maya, Motion Builder and 3D Max?

**Comment by emilianavt** [comment]
Hi, I do not have access to any of those softwares so I cannot test. Did the error show any details about what the issue with the file could be?

**Comment by YouMinJung** [comment]
When I open the BVH file in 3D Max, Maya and Motion Builder, I get these error.

![캡처](https://user-images.githubusercontent.com/21214309/133565566-fd0fc9d5-e7c5-4e31-afb1-01f12594dc0d.PNG)

![캡처1](https://user-images.githubusercontent.com/21214309/133565584-17c8db13-f82c-4c08-9108-692181ca0389.PNG)


How can I solve these problem..??

**Comment by emilianavt** [comment]
BVHTools uses either the names of the bones on the model it is recording from or Unity's humanoid bones. It seems like these tools expect the hierarchy to use different, specific names. If you can find a list of expected names, you can edit the upper hierarchy part of the BVH file using a text editor to rename the bones accordingly.

Alternatively, you could try loading it into Blender or another BVH editor and rename things there.
